import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        input: "rgb(var(--input-rgb) / <alpha-value>)",
        ring: "rgb(var(--ring-rgb) / <alpha-value>)",
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        foreground: "rgb(var(--foreground-rgb) / <alpha-value>)",
        primary: {
          DEFAULT: "rgb(var(--primary-rgb) / <alpha-value>)",
          foreground: "rgb(var(--primary-foreground-rgb) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary-rgb) / <alpha-value>)",
          foreground: "rgb(var(--secondary-foreground-rgb) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive-rgb) / <alpha-value>)",
          foreground: "rgb(var(--destructive-foreground-rgb) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "rgb(var(--muted-rgb) / <alpha-value>)",
          foreground: "rgb(var(--muted-foreground-rgb) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--accent-rgb) / <alpha-value>)",
          foreground: "rgb(var(--accent-foreground-rgb) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "rgb(var(--popover-rgb) / <alpha-value>)",
          foreground: "rgb(var(--popover-foreground-rgb) / <alpha-value>)",
        },
        card: {
          DEFAULT: "rgb(var(--card-rgb) / <alpha-value>)",
          foreground: "rgb(var(--card-foreground-rgb) / <alpha-value>)",
        },
        surface: {
          page: "var(--surface-page)",
          card: "var(--surface-card)",
          subtle: "var(--surface-subtle)",
          hover: "var(--surface-hover)",
          elevated: "var(--surface-elevated)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          disabled: "var(--text-disabled)",
          inverse: "var(--text-inverse)",
        },
        action: {
          primary: "var(--primary)",
          "primary-hover": "var(--primary-hover)",
          secondary: "var(--surface-card)",
          "secondary-hover": "var(--surface-subtle)",
          ghost: "transparent",
          "ghost-hover": "var(--surface-hover)",
        },
        status: {
          success: {
            bg: "var(--success-bg)",
            fg: "var(--success-fg)",
            border: "var(--success-border)",
            icon: "var(--success-icon)",
          },
          warning: {
            bg: "var(--warning-bg)",
            fg: "var(--warning-fg)",
            border: "var(--warning-border)",
            icon: "var(--warning-icon)",
          },
          danger: {
            bg: "var(--danger-bg)",
            fg: "var(--danger-fg)",
            border: "var(--danger-border)",
            icon: "var(--danger-icon)",
          },
          info: {
            bg: "var(--info-bg)",
            fg: "var(--info-fg)",
            border: "var(--info-border)",
            icon: "var(--info-icon)",
          },
        },
        navigation: {
          background: "var(--nav-background)",
          border: "var(--nav-border)",
          text: "var(--nav-text)",
          "text-muted": "var(--nav-text-muted)",
          active: "var(--nav-active)",
          "active-text": "var(--nav-active-text)",
          hover: "var(--nav-hover)",
          "hover-text": "var(--nav-hover-text)",
        },
        placeholder: "var(--placeholder-color)",
        focus: {
          DEFAULT: "var(--focus-ring)",
          offset: "var(--focus-ring-offset)",
        },
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "rgb(var(--sidebar-background-rgb) / <alpha-value>)",
          foreground: "rgb(var(--sidebar-foreground-rgb) / <alpha-value>)",
          primary: "rgb(var(--sidebar-primary-rgb) / <alpha-value>)",
          "primary-foreground": "rgb(var(--sidebar-primary-foreground-rgb) / <alpha-value>)",
          accent: "rgb(var(--sidebar-accent-rgb) / <alpha-value>)",
          "accent-foreground": "rgb(var(--sidebar-accent-foreground-rgb) / <alpha-value>)",
          border: "rgb(var(--sidebar-border-rgb) / <alpha-value>)",
          ring: "rgb(var(--sidebar-ring-rgb) / <alpha-value>)",
        },
      },
      spacing: {
        "ui-1": "var(--space-1)",
        "ui-2": "var(--space-2)",
        "ui-3": "var(--space-3)",
        "ui-4": "var(--space-4)",
        "ui-5": "var(--space-5)",
        "ui-6": "var(--space-6)",
        "ui-8": "var(--space-8)",
        "ui-10": "var(--space-10)",
        "ui-12": "var(--space-12)",
        "ui-16": "var(--space-16)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
        DEFAULT: "var(--radius-md)",
      },
      boxShadow: {
        surface: "var(--shadow-surface)",
        dropdown: "var(--shadow-dropdown)",
        dialog: "var(--shadow-dialog)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        normal: "var(--motion-normal)",
        slow: "var(--motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
      },
      fontSize: {
        display: ["2.25rem", { lineHeight: "2.5rem", fontWeight: "700", letterSpacing: "-0.02em" }],
        "page-title": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "700", letterSpacing: "-0.02em" }],
        "section-title": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600", letterSpacing: "-0.01em" }],
        "card-title": ["1rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        body: ["0.875rem", { lineHeight: "1.3125rem", fontWeight: "400" }],
        "body-strong": ["0.875rem", { lineHeight: "1.3125rem", fontWeight: "600" }],
        small: ["0.8125rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        caption: ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        label: ["0.75rem", { lineHeight: "1rem", fontWeight: "600" }],
        "table-header": ["0.75rem", { lineHeight: "1rem", fontWeight: "600", letterSpacing: "0.02em" }],
        "table-body": ["0.8125rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "financial-metric": ["1.75rem", { lineHeight: "2.125rem", fontWeight: "700", letterSpacing: "-0.02em" }],
      },
    },
  },
  plugins: [],
};

export default config;
